### ISSUE TITLE
Usage with iPad?

### ISSUE THREAD

**Issue by muuuh** [MatthewYork/iPhone-IntroductionTutorial#1]
Hi,

could you please add iPad support?
Thanks!

**Comment by MatthewYork** [comment]
I will look at this in the upcoming week. Shouldn't take too much tweaking to get iPad support. Styling it appropriately may be an interesting challenge. I'll update here when I have something.

**Comment by mamcx** [comment]
I find weird that you have a XIB but don't use it at all (all the layout is by code!)

**Comment by MatthewYork** [comment]
Yeah, I added it in there for the initial styling (just to get a feel for things), and then forgot to take it out. I'll go ahead and remove it. Good find!

**Comment by MatthewYork** [comment]
@mamcx xib file has been removed.

**Comment by ghost** [comment]
Change the device target to "Universal" and change the view frames to dynamic style. It will work for both iPhone and iPad.

**Comment by muuuh** [comment]
@Mohan-77: Sure, you have to set the device target to universal, but my issue is, that the content isn't aligned corrently (lower text, image in vertical center, more padding).

The frame is already set "dynamic" in the sample code:
    MYIntroductionView *introductionView = [[MYIntroductionView alloc] initWithFrame:CGRectMake(0, 0, self.view.frame.size.width, self.view.frame.size.height) headerText:@"MYIntroductionView" panels:@[panel, panel2] languageDirection:MYLanguageDirectionLeftToRight];

But it leads to the attached screen
![iOS Simulator Bildschirmfoto 27 03 2013 08 43 10](https://f.cloud.github.com/assets/3055083/307154/808def16-96b2-11e2-936c-26dc8922294b.png)

**Comment by ghost** [comment]
so while setting the frame check the condition whether the device is ipad or other and based on the device set the frame.

you can check the device using "[UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad".

**Comment by muuuh** [comment]
Just leave out the basics and provide a real solution ;) MYIntroductionView.m needs a change

**Comment by MatthewYork** [comment]
I agree that it needs a change. I was looking into it, actually and feel like it wouldn't be too bad to wrap and center the intro content. Also, I'm planning on putting an upper bound on the panel description width so it doesn't span the entirety of the screen. 

From its inception, this class was never meant for use on the iPad, but it may be adaptable.

**Comment by nilskasseckert** [comment]
When you write this:
IntroductionView *introductionView = [[MYIntroductionView alloc] initWithFrame:CGRectMake(0, 0, self.view.bounds.size.width, self.view.bounds.size.height) headerText:@"MYIntroductionView" panels:@[panel, panel2] languageDirection:MYLanguageDirectionLeftToRight];

It work's on iPad, iPhone, iPod Touch

**Comment by Akhrameev** [comment]
I use IntroductionView for iPad, too.

IntroductionView *introductionView = [[MYIntroductionView alloc] initWithFrame:self.view.bounds headerText:@"" panels:@[panel, panel2] languageDirection:MYLanguageDirectionLeftToRight];
Is a bit shorter. But how did you realized changes on rotation. As for me, background image doesn't cover all view.

After [introductionView setAutoresizingMask:UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight]; it fills uncovered with black color and doesn't change text height and so on. What should I do?

**Comment by nilskasseckert** [comment]
I had the same problem and I forbid the autorate with: 
iOS6:
-(BOOL)shouldAutorotate {
    return NO;
}

iOS5:
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
  return NO;
  }
  (Sorry for my bad Englisch!)

**Comment by Akhrameev** [comment]
Thank you! I'll rewrite my Navigation Controller to block rotation, while showing IntroductionView.

**Comment by pdashford** [comment]
Same issue, here the page control resizes to the content where-as this should stay at the bottom of the screen no matter how much content is shown. Has anyone done an update to push this to the bottom of the screen?

**Comment by MatthewYork** [comment]
iPad usage should now be fixed.
