### ISSUE TITLE
iOS 7 - Text not showing

### ISSUE THREAD

**Issue by phldgmn** [MatthewYork/iPhone-IntroductionTutorial#10]
Experienced on iPhone 5 running iOS 7 beta 1 & 2 until now, the images are showing fine, also the page-control is working, only the text is not displayed.

Thank you for taking care.

**Comment by vinhnx** [comment]
I have the same problem.

Header, Image, page control are fine. But the text is missing.

**Comment by alexwald** [comment]
I experience the same/

**Comment by phldgmn** [comment]
But I tried it now on a Beta 3 Device with the App from the App Store - there it seems to be working, so I think, it's a Emulator- / xCode-related issue...

**Comment by alexwald** [comment]
nope.
the thing is that the UITextView compiled for iOS6 is backed by UIWebDocumentView, whereas under iOS7 it has been revamped using TextKit, where the backing is provided by UITextContainerView <- which seems to be the problem here.

**Comment by MatthewYork** [comment]
Thanks to everyone for doing the research. I've used all 3 betas, and I noticed slightly different results for labels and textviews for iOS 6 compiled apps in each. That said, I feel it wise to wait to address any bugs seen using iOS 7 until closer to release (preferably around Gold Master). I will leave this thread open to address problems when the time comes.

**Comment by zdsumit** [comment]
Hello All, I am using beta 6 and xcode 5 . I am also facing problem related to UITEXTVIEW and UILABEL , when a user types text in it, there is a shift downwards. And the same thing works properly in ios6. 
If anybody can reproduce the same, let me know and lets tackle it down together.

**Comment by MatthewYork** [comment]
Gold Master is here and, as promised, you have your changes for iOS 7. You should be fully compatible now for iPhone and iPad on all recent iterations of iOS. Let me know if you guys find any other problems and I will get them fixed

**Comment by phldgmn** [comment]
Looks great! Only thing I noticed is that if the text just breaks into two lines (not more), the last line is not visible. I just added another 13.0f to the descriptionHeight in -(UIView _)PanelViewForPanel:(MYIntroductionPanel *)panel atXIndex:(CGFloat_)xIndex and it showed up. Seems to be a bug in panelDescriptionTextView.frame.size.height...

**Comment by MatthewYork** [comment]
Interesting... I haven't seen that! Let's continue to look at the PanelViewForPanel method and see if there is anything we are missing here with the frame construction. I honestly don't see it.

**Comment by zdsumit** [comment]
Yes, its true... I am using new Xcode 5 GM seed and also GM seed version of ios7 on my devices but still problem is there. The text view shifts by height of 1 line while typing and becomes normal after editing is done. Same thing works properly in IOS6 devices
