### ISSUE TITLE
How to show the SkipButton? Thanks

### ISSUE THREAD

**Issue by cocoajin** [MatthewYork/iPhone-IntroductionTutorial#12]
How to show the SkipButton? Thanks

**Comment by cocoajin** [comment]
the SkipButton showed;
Why the SkipButton dose not show in your demo project?

**Comment by MatthewYork** [comment]
I have been attending to other projects as of late, but hopefully soon I will get the bugs worked out of this one. We had some problems merging changes from a few forks. Once things slow down, I will get this fixed.

**Comment by yinsee** [comment]
please merge my pull request which i have fixed the skip button (wrong X position)

**Comment by MatthewYork** [comment]
The skip button shows now (and is localized), so I am going to close this issue.
