### ISSUE TITLE
Description text gets truncated to one line

### ISSUE THREAD

**Issue by duncsand** [MatthewYork/iPhone-IntroductionTutorial#16]
It seems that the description field is always truncated to a single line, regardless of how much text there is. This is running on iPhone.

**Comment by MatthewYork** [comment]
I have a solution for this, but have been very busy. I will get it fixed up for you soon.

**Comment by MatthewYork** [comment]
This issue should now be resolved.

**Comment by duncsand** [comment]
Confirmed fixed - great job!
