### ISSUE TITLE
New tagged release for cocoapods?

### ISSUE THREAD

**Issue by phillbaker** [MatthewYork/iPhone-IntroductionTutorial#17]
Hey, I'd love to see this get included in the official https://github.com/CocoaPods/Specs/ repo. I'd be happy to submit that PR, but it'd probably be good to submit an updated podspec.

Would you be comfortable tagging and releasing a recent commit as something greater than `0.0.1`?

**Comment by MatthewYork** [comment]
I'm about to fix the problems with iOS 7 text clipping and also merge the custom view pull request that is currently pending. After that, I will update the podspec. Thanks for reminding me. I had totally forgotten about it.

**Comment by phillbaker** [comment]
Great! I submitting the original podspec here (https://github.com/CocoaPods/Specs/pull/4708) and can update as need be.

**Comment by MatthewYork** [comment]
Hey, Phil!

I just made a pull request with the most recent MYIntroduction commit for Cocoa Pods. This one should have the iOS 7 updates and custom contnt view.
