### ISSUE TITLE
iphone5 layout?

### ISSUE THREAD

**Issue by adad184** [MatthewYork/iPhone-IntroductionTutorial#5]
as your pics in README,  in iphone5   there's some space at the bottom of the iphone , should adjust to fit the fullscreen?

**Comment by MatthewYork** [comment]
Are you creating the introduction in viewDidLoad? I have noticed that sometimes the self.view object does not resize until viewDidAppear, hence the white space. Still, I will try to fix the auto resize madk to handle this. Good find.

**Comment by adad184** [comment]
i add it in the appdelegate init method & i made some modifications for my demand

padding the headerView to TOP 20px because i added it to the UIWindow (i think most apps using the introductionView is navigation-based, so may be better on the UIWindow & calculate the statusbar height)

set autoresizingMask for every subViews & make the ContentView Center & the pageControl,SkipButton close to the bottom but not related to the ContentView

**Comment by adad184** [comment]
so i think  the padding to the top & bottom would better to be configurable

**Comment by cjazz** [comment]
My way around this was to take the more customized method from the example, and set headerText:@"".  It leaves space on top, however it utilizes most of the bottom.  Doesn't fully answer adad184's issue, but it helps I think.

**Comment by MatthewYork** [comment]
iPhone 5 layout should be good now for iOS 6 and 7. I'm going to go ahead and close this issue.
