### ISSUE TITLE
MYIntroductionView does not rotate properly?

### ISSUE THREAD

**Issue by hankinsoft** [MatthewYork/iPhone-IntroductionTutorial#6]
Hello,
If you have a MYIntroductionView and your viewcontroller supports rotation, the MYIntroductionView does not properly rotate. Instead it takes up part of the screen.

See: http://imgur.com/KGObRTv

**Comment by shams-ahmed** [comment]
Hello, i forked this project and updated it so it support multiple devices and orientation...

project link: https://github.com/shams-ahmed/iPhone-IntroductionTutorial-Orientation

**Comment by zoelounge** [comment]
hello shams-ahmed i test your fork project but it's ok only if i start in portrait view.
If a start in landscape view on iPad and switch in portrait view it's does not properly rotate, as say hankinsoft on "MYIntroductionView does not rotate properly?"

thank you.

**Comment by MatthewYork** [comment]
This has been addressed and should now work fine (although iPhone landscape is not recommended).

**Comment by zoelounge** [comment]
I have solution that work fine on iPad and iPhone
