### ISSUE TITLE
Image not showing in panel

### ISSUE THREAD

**Issue by alvaronuwit** [MatthewYork/iPhone-IntroductionTutorial#8]
Hi there, i have some issues with the image in a panel. In the simulator you can see the image, but not on the device (ios 6.0).
Regards

**Comment by shams-ahmed** [comment]
could be one of the following:
1. image hasn't been included in your app bundle.
2. Check the capitalization of your filenames

try deleting image on xcode and reinserting making sure that its copy to your target

**Comment by alvaronuwit** [comment]
Thanks man, I gonna try the solutions you gave me.
